# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb545de5fb2848e32cd3bf6ff0ed607388f43d15877fd4ff7ef3e498566d3972a06af8611fff453c844d8bb985764f32cf7cf280e399813a88a87e338edb6a9c

test:
  secret_key_base: 5acab668443b59335e49578192de539ece8b0f325c17cb3ff7e5e69a9a036b1d092f4fdee3a1438700445eb9ab03ed2a09749ba09963d26b5877ccce4c0cc7e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
